services:
  fakerweb:
    build:
      context: ..
      dockerfile: config/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        LINUX_DIST: ${LINUX_DIST:-ubuntu}
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
      - ../src/image/share:/var/www/html/image/share
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    user: "www-data:www-data"
    privileged: true
    depends_on:
      - fakerdb
    networks:
      - app-network

  fakerdb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: fakerDB
      MYSQL_USER: faker
      MYSQL_PASSWORD: F4k3r_1s_H4rd_T0_Gu3ss
    volumes:
      - db_data:/var/lib/mysql
      - ./fakerDB.sql:/docker-entrypoint-initdb.d/fakerDB.sql
    networks:
      - app-network

  waf-nginx:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./modsecurity.conf:/etc/modsecurity/modsecurity.conf:ro
      - ./crs:/etc/nginx/modsec-crs:ro
    depends_on:
      - fakerweb
    environment:
      - MODSECURITY_ENABLE=true
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge